# frozen_string_literal: true

RSpec.describe Serega::SeregaAttributeNormalizer do
  let(:serializer_class) { Class.new(Serega) }
  let(:normalizer) { serializer_class::SeregaAttributeNormalizer }

  describe "#name" do
    it "symbolizes name" do
      attribute = normalizer.new(name: "current_name")
      expect(attribute.name).to eq :current_name
    end
  end

  describe "#method_name" do
    it "returns symbolized :method options" do
      attribute = normalizer.new(name: "current_name", opts: {method: "method"})
      expect(attribute.method_name).to eq :method
    end

    it "returns name when :method option not provided" do
      attribute = normalizer.new(name: "current_name", opts: {})
      expect(attribute.method_name).to eq :current_name
    end
  end

  describe "#many" do
    it "returns provided :many option" do
      expect(normalizer.new(opts: {many: true}).many).to be true
      expect(normalizer.new(opts: {many: false}).many).to be false
      expect(normalizer.new(opts: {}).many).to be_nil
    end

    it "returns saved :many option" do
      norm = normalizer.new(opts: {many: true})

      expect(norm.many).to be true
      expect(norm.instance_variable_get(:@many)).to be true

      norm.instance_variable_set(:@many, nil)
      expect(norm.many).to be_nil
    end
  end

  describe "#serializer" do
    it "returns provided :serializer option" do
      expect(normalizer.new(opts: {serializer: 123}).serializer).to eq 123
    end

    it "returns saved :serializer option" do
      norm = normalizer.new(opts: {serializer: true})

      expect(norm.serializer).to be true
      expect(norm.instance_variable_get(:@serializer)).to be true

      norm.instance_variable_set(:@serializer, nil)
      expect(norm.serializer).to be_nil
    end
  end

  describe "#prepare_value_block" do
    it "returns provided block" do
      block = lambda { 123 }
      attribute = normalizer.new(block: block, opts: {})
      value_block = attribute.send(:prepare_value_block)
      expect(value_block).to equal block
    end

    it "returns provided value option" do
      value = lambda { |one, two| }
      attribute = normalizer.new(opts: {value: value})
      expect(attribute.send(:prepare_value_block)).to equal value
    end

    it "returns block generated by :method option" do
      block = normalizer.new(opts: {method: :length}).send(:prepare_value_block)
      expect(block).to be_a Proc
      expect(block.call(double(length: 3))).to eq 3
    end

    it "returns block generated by :const option" do
      const = "123"
      block = normalizer.new(opts: {const: const}).send(:prepare_value_block)
      expect(block).to be_a Proc
      expect(block.call).to be const
    end

    it "returns block generated by :delegate option when nil is not allowed" do
      object = double(foo: double(name: "DELEGATED_NAME"))
      delegate = {to: :foo}
      block = normalizer.new(name: :name, opts: {delegate: delegate}).send(:prepare_value_block)
      expect(block).to be_a Proc
      expect(block.call(object)).to eq "DELEGATED_NAME"
    end

    it "returns block generated by :delegate option that uses :method option" do
      object = double(foo: double(bar: "DELEGATED_NAME"))
      delegate = {to: :foo, method: :bar}
      block = normalizer.new(opts: {delegate: delegate}).send(:prepare_value_block)
      expect(block).to be_a Proc
      expect(block.call(object)).to eq "DELEGATED_NAME"
    end

    it "does not raise error when :delegating object is nil and nil is allowed" do
      object1 = double(foo: nil)
      object2 = double(foo: double(name: "NAME"))
      delegate = {to: :foo, allow_nil: true}
      block = normalizer.new(name: :name, opts: {delegate: delegate}).send(:prepare_value_block)
      expect(block).to be_a Proc
      expect(block.call(object1)).to be_nil
      expect(block.call(object2)).to eq "NAME"
    end

    it "does not raise error when :delegating object is nil and nil is allowed through config" do
      object1 = double(foo: nil)
      object2 = double(foo: double(name: "NAME"))
      delegate = {to: :foo}
      serializer_class.config.delegate_default_allow_nil = true
      block = normalizer.new(name: :name, opts: {delegate: delegate}).send(:prepare_value_block)
      expect(block).to be_a Proc
      expect(block.call(object1)).to be_nil
      expect(block.call(object2)).to eq "NAME"
    end
  end

  describe "preloads functionality" do
    let(:initials) { {name: :foo, opts: opts, block: nil} }
    let(:opts) { {} }
    let(:norm) { normalizer.new(**initials) }

    describe "#preloads" do
      it "returns empty hash for regular attributes" do
        expect(norm.preloads).to eq({})
      end

      it "returns nil when provided nil" do
        opts[:preload] = nil
        expect(norm.preloads).to be_nil
      end

      it "returns formatted provided preloads" do
        opts[:preload] = :bar
        expect(norm.preloads).to eq(bar: {})
        expect(norm.preloads).to equal norm.preloads
      end

      it "returns automatically found preloads when serializer provided" do
        serializer_class.config.auto_preload_attributes_with_serializer = true
        opts[:serializer] = "bar"
        expect(norm.preloads).to eq(foo: {})
      end

      it "returns no preloads for attributes with serializer by default" do
        opts[:serializer] = "bar"
        expect(norm.preloads).to eq({})
      end

      it "returns automatically found preloads when :delegate option provided" do
        serializer_class.config.auto_preload_attributes_with_delegate = true
        opts[:delegate] = {to: :bar}
        expect(norm.preloads).to eq(bar: {})
      end

      it "returns no preloads for attributes with :delegate option by default" do
        opts[:delegate] = {to: :bar}
        expect(norm.preloads).to eq({})
      end
    end

    describe "#preloads_path" do
      it "returns constructed preloads_path" do
        opts[:preload] = :foo
        expect(norm.preloads_path).to eq([:foo])
        expect(norm.preloads_path).to be_frozen
        expect(norm.preloads_path).to equal norm.preloads_path
      end

      it "returns provided preloads_path" do
        opts[:serializer] = "foo"
        opts[:preload] = %i[bar bazz]
        opts[:preload_path] = :bar
        expect(norm.preloads_path).to eq([:bar])
        expect(norm.preloads_path).to be_frozen
      end

      it "returns symbolized preloads_path" do
        opts[:serializer] = "foo"
        opts[:preload] = %i[bar bazz]
        opts[:preload_path] = "bar"
        expect(norm.preloads_path).to eq([:bar])
      end

      it "returns symbolized preloads_path when array provided" do
        opts[:serializer] = "foo"
        opts[:preload] = %i[bar bazz]
        opts[:preload_path] = %w[bar]
        expect(norm.preloads_path).to eq([:bar])
      end

      it "returns normalized array of provided paths" do
        opts[:serializer] = "foo"
        opts[:preload] = %i[bar bazz]
        opts[:preload_path] = [["bar"], ["bar", :bazz]]
        expect(norm.preloads_path).to eq([%i[bar], %i[bar bazz]])
        expect(norm.preloads_path).to be_frozen
      end

      it "returns nil if nil provided" do
        opts[:serializer] = "foo"
        opts[:preload] = %i[bar bazz]
        opts[:preload_path] = nil
        expect(norm.preloads_path).to be_nil
      end
    end

    describe "#hide with preloads" do
      context "without auto_hide config" do
        it "returns opt :hide" do
          a0 = serializer_class.attribute :a0
          a1 = serializer_class.attribute :a1, preload: :a1
          a2 = serializer_class.attribute :a2, preload: :a2, hide: true
          a3 = serializer_class.attribute :a3, preload: :a3, hide: false

          expect(a0.hide).to be_nil
          expect(a1.hide).to be_nil
          expect(a2.hide).to be true
          expect(a3.hide).to be false
        end

        it "returns saved :hide option" do
          norm = normalizer.new(opts: {hide: true})

          expect(norm.hide).to be true
          expect(norm.instance_variable_get(:@hide)).to be true

          norm.instance_variable_set(:@hide, nil)
          expect(norm.hide).to be_nil
        end
      end

      context "with auto_hide config" do
        before do
          serializer_class.config.auto_hide_attributes_with_preload = true
        end

        it "returns opt :hide => true when preload is not blank" do
          a0 = serializer_class.attribute :a0
          a1 = serializer_class.attribute :a1, preload: :a1
          a2 = serializer_class.attribute :a2, preload: :a2, hide: true
          a3 = serializer_class.attribute :a3, preload: :a3, hide: false
          a4 = serializer_class.attribute :a4, preload: nil
          a5 = serializer_class.attribute :a5, preload: false
          a6 = serializer_class.attribute :a6, preload: {}
          a7 = serializer_class.attribute :a7, preload: []

          expect(a0.hide).to be_nil
          expect(a1.hide).to be true
          expect(a2.hide).to be true
          expect(a3.hide).to be false
          expect(a4.hide).to be_nil
          expect(a5.hide).to be_nil
          expect(a6.hide).to be_nil
          expect(a7.hide).to be_nil
        end
      end
    end
  end
end
